### ISSUE TITLE
Standardize code

### ISSUE THREAD

**Issue by Demfier** [Demfier/GitPub#14]
Although the library was meant to be both python3 and python2 compatible. There are still a few irregularities like in [here](https://github.com/Demfier/GitPub/blob/master/gitpub/gitpub.py#L102).
Similarly all the `print ("Something")` should be `print("Something")`

Anything beyond 80 characters should be put on the next line as in [here](https://github.com/Demfier/GitPub/blob/master/gitpub/gitpub.py#L2)

**Comment by ydjain** [comment]
So basically we want flake8 not to return any warnings or errors??

Can You assign me this issue?

**Comment by Demfier** [comment]
Yeah, exactly.

**Comment by Demfier** [comment]
@ydjain - I am adding you as a collaborator. Please accept the collaborator-invite and self-assign this issue to yourself.

**Comment by ydjainopensource** [comment]
#16 

I have changed the files as required... can you send a collaboration invite to this Id too??

**Comment by Demfier** [comment]
Ok sent. I suppose you will contribute using this same id.

Also, I have reviewed you PR. Have a look at it.

**Comment by Demfier** [comment]
Fixed via #16

**Comment by Demfier** [comment]
Fixed via #16
